"""clinic time zone

Revision ID: b039b7a41fb4
Revises: cee8cd8ad30f
Create Date: 2026-09-25 05:58:20.187111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b039b7a41fb4'
down_revision = 'cee8cd8ad30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='Africa/Harare', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
