"""initial schema: organizations, users, patients, assessments, audit

Revision ID: cee8cd8ad30f
Revises: 
Create Date: 2026-09-25 05:32:00.684010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee8cd8ad30f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('require_mfa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_last_counter', sa.BigInteger(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_org_id'), ['org_id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_org_id'), ['org_id'], unique=False)

    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'mrn', name='uq_patient_org_mrn')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_org_id'), ['org_id'], unique=False)

    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=10), nullable=False),
    sa.Column('positive', sa.Boolean(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('ptp', sa.Float(), nullable=True),
    sa.Column('ptp_note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_patient_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_org_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_created_at'))

    op.drop_table('assessment')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_org_id'))

    op.drop_table('patient')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_created_at'))

    op.drop_table('audit_event')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_org_id'))

    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###
